version: '3'

services:
  spring-boot-app:
    image: da-task
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker-container:3306/da-task
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

  mysql-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=da-task
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    networks:
      - mynetwork

networks:
  mynetwork:

